name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/all-screens/images/indir-5-1.png
    - assets/all-screens/images/vizz-1.png
    - assets/all-screens/images/vector-14.png
    - assets/all-screens/images/iconly-light-outline-filter.png
    - assets/all-screens/images/image-10.png
    - assets/all-screens/images/images-3-1.png
    - assets/all-screens/images/searchbar.png
    - assets/all-screens/images/vector-94.png
    - assets/all-screens/images/product-category-icons.png
    - assets/all-screens/images/vector.png
    - assets/all-screens/images/image-8.png
    - assets/all-screens/images/frame-10.png
    - assets/all-screens/images/fill.png
    - assets/all-screens/images/vizz-1-NtM.png
    - assets/all-screens/images/iconly-bold-star.png
    - assets/all-screens/images/track.png
    - assets/all-screens/images/mask-group.png
    - assets/all-screens/images/vector-14-kLM.png
    - assets/all-screens/images/iconly-bold-star-3Cy.png
    - assets/all-screens/images/indir-7-1.png
    - assets/all-screens/images/icons.png
    - assets/all-screens/images/image-8-3Qy.png
    - assets/all-screens/images/component-1.png
    - assets/all-screens/images/frame-10-293.png
    - assets/all-screens/images/product-category-icons-8Sy.png
    - assets/all-screens/images/indir-8-1.png
    - assets/all-screens/images/vector-14-T1w.png
    - assets/all-screens/images/mask-group-A4d.png
    - assets/all-screens/images/image-8-9SM.png
    - assets/all-screens/images/iconly-bold-star-rrZ.png
    - assets/all-screens/images/mask-group-35o.png
    - assets/all-screens/images/icons-D49.png
    - assets/all-screens/images/vector-14-DnD.png
    - assets/all-screens/images/iconly-light-outline-search.png
    - assets/all-screens/images/product-category-icons-koP.png
    - assets/all-screens/images/vector-12.png
    - assets/all-screens/images/track-Yv9.png
    - assets/all-screens/images/rectangle-11106.png
    - assets/all-screens/images/heart-solid.png
    - assets/all-screens/images/track-RZo.png
    - assets/all-screens/images/product-category-icons-io7.png
    - assets/all-screens/images/iconly-bold-star-9Vf.png
    - assets/all-screens/images/vector-14-jPK.png
    - assets/all-screens/images/image-8-4Rb.png
    - assets/all-screens/images/iconly-bold-star-EBX.png
    - assets/all-screens/images/product-category-icons-Roj.png
    - assets/all-screens/images/vector-14-y4Z.png
    - assets/all-screens/images/vector-14-zww.png
    - assets/all-screens/images/vizz-1-hbT.png
    - assets/all-screens/images/vizz-1-EbP.png
    - assets/all-screens/images/fill-x1b.png
    - assets/all-screens/images/indir-6-1.png
    - assets/all-screens/images/indir-1.png
    - assets/all-screens/images/image-8-xvh.png
    - assets/all-screens/images/product-category-icons-jDF.png
    - assets/all-screens/images/vector-14-4HT.png
    - assets/all-screens/images/rectangle-11106-JxV.png
    - assets/all-screens/images/icons-6vH.png
    - assets/all-screens/images/icons-xUd.png
    - assets/all-screens/images/iconly-bold-star-7jT.png
    - assets/all-screens/images/vector-14-tZB.png
    - assets/all-screens/images/iconly-bold-3-user.png
    - assets/all-screens/images/vector-14-Zm7.png
    - assets/all-screens/images/vector-14-gtu.png
    - assets/all-screens/images/component-1-h6V.png
    - assets/all-screens/images/component-1-bgy.png
    - assets/all-screens/images/sgzaoxz7zye91-1.png
    - assets/all-screens/images/icons-M8y.png
    - assets/all-screens/images/component-1-KFT.png
    - assets/all-screens/images/vector-14-eMb.png
    - assets/all-screens/images/icons-Em3.png
    - assets/all-screens/images/component-1-WMB.png
    - assets/all-screens/images/iconly-bold-star-giq.png
    - assets/all-screens/images/component-1-6Zb.png
    - assets/all-screens/images/iconly-bold-star-e7F.png
    - assets/all-screens/images/vector-14-qHX.png
    - assets/all-screens/images/vector-14-b3j.png
    - assets/all-screens/images/component-1-S85.png
    - assets/all-screens/images/component-1-d1P.png
    - assets/all-screens/images/vector-94-yXj.png
    - assets/all-screens/images/mask-group-tUu.png
    - assets/all-screens/images/group-128.png
    - assets/all-screens/images/component-1-63f.png
    - assets/all-screens/images/mask-group-yt9.png
    - assets/all-screens/images/fill-TNd.png
    - assets/all-screens/images/component-1-WmT.png
    - assets/all-screens/images/group-128-4h3.png
    - assets/all-screens/images/iconly-bold-star-KTj.png
    - assets/all-screens/images/iconly-bold-edit-square.png
    - assets/all-screens/images/vector-14-Tuw.png
    - assets/all-screens/images/component-1-iJh.png
    - assets/all-screens/images/app-navigation.png
    - assets/all-screens/images/vector-12-nZB.png
    - assets/all-screens/images/rectangle-11106-fmF.png
    - assets/all-screens/images/app-navigation-nzq.png
    - assets/all-screens/images/hamburger-menu.png
    - assets/all-screens/images/icons-bz5.png
    - assets/all-screens/images/component-1-xNh.png
    - assets/all-screens/images/image-5.png
    - assets/all-screens/images/intersect.png
    - assets/all-screens/images/image-6.png
    - assets/all-screens/images/vector-14-bXT.png
    - assets/all-screens/images/vector-14-pRT.png
    - assets/all-screens/images/vector-1J5.png
    - assets/all-screens/images/vector-aP7.png
    - assets/components/images/property-1shop.png
    - assets/all-screens/images/searchbar-TeM.png
    - assets/components/images/group-23.png
    - assets/all-screens/images/vector-12-tWR.png
    - assets/all-screens/images/depositphotos83462502-stock-illustration-gun-toy-1.png
    - assets/components/images/vector-Nmb.png
    - assets/all-screens/images/rectangle-11106-CBX.png
    - assets/components/images/property-1stats.png
    - assets/all-screens/images/iconly-bold-star-MQR.png
    - assets/components/images/vector-14-xgM.png
    - assets/all-screens/images/vector-14-rKo.png
    - assets/components/images/property-1home.png
    - assets/all-screens/images/app-navigation-cgu.png
    - assets/components/images/group-9.png
    - assets/all-screens/images/component-1-Uhj.png
    - assets/components/images/property-1profile.png
    - assets/all-screens/images/vector-94-MEu.png
    - assets/all-screens/images/vector-14-Se9.png
    - assets/components/images/vector-14-Cj7.png
    - assets/all-screens/images/group.png
    - assets/all-screens/images/image-5-2EH.png
    - assets/all-screens/images/component-1-kds.png
    - assets/all-screens/images/mask-group-ntu.png
    - assets/components/images/iconly-light-outline-search-7w3.png
    - assets/components/images/cruelty-free.png
    - assets/components/images/eco-friendly.png
    - assets/components/images/iconly-light-outline-filter-7df.png
    - assets/all-screens/images/frame-10-aQm.png
    - assets/components/images/group-6.png
    - assets/components/images/iconly-light-outline-search-EDj.png
    - assets/components/images/vector-14-biV.png
    - assets/components/images/cruelty-free-KuP.png
    - assets/components/images/fill-yyw.png
    - assets/components/images/eco-friendly-JmK.png
    - assets/components/images/track-SYd.png
    - assets/components/images/vegan.png
    - assets/components/images/vegan-XM7.png
    - assets/components/images/fill-SDB.png
    - assets/components/images/track-Ncd.png
    - assets/components/images/fill-JmB.png
    - assets/all-screens/images/depositphotos85555696-stock-illustration-dinosaurus-toy-1.png
    - assets/all-screens/images/indir-2-1.png
    - assets/components/images/group-24.png
    - assets/components/images/vector-14-53T.png
    - assets/components/images/image-5-5qP.png
    - assets/components/images/eco-friendly-4e1.png
    - assets/components/images/track-v4d.png
    - assets/components/images/fill-Tgy.png
    - assets/components/images/maps-bg.png
    - assets/components/images/track-ty3.png
    - assets/components/images/fill-1x9.png
    - assets/components/images/track-oYH.png
    - assets/all-screens/images/app-navigation-rqs.png
    - assets/all-screens/images/group-74.png
    - assets/components/images/group-21.png
    - assets/components/images/fill-tEy.png
    - assets/components/images/track-Mph.png
    - assets/components/images/image-8-yiV.png
    - assets/components/images/vegan-5sj.png
    - assets/components/images/iconly-bold-star-ZuX.png
    - assets/components/images/iconly-bold-star-Yzy.png
    - assets/components/images/group-22.png
    - assets/components/images/iconly-bold-star-8zy.png
    - assets/components/images/mask-group-W5b.png
    - assets/components/images/group-138.png
    - assets/components/images/mask-group-kSH.png
    - assets/components/images/iconly-bold-star-nA1.png
    - assets/components/images/mask-group-snM.png
    - assets/components/images/iconly-bold-star-xDT.png
    - assets/components/images/cruelty-free-Pzm.png
    - assets/components/images/icons-zv1.png
    - assets/components/images/icons-zKf.png
    - assets/components/images/icons-ncD.png
    - assets/components/images/group-140.png
    - assets/components/images/group-141.png
    - assets/components/images/group-137.png
    - assets/components/images/icons-sGH.png
    - assets/components/images/icons-TYZ.png
    - assets/components/images/typenotifications-statedefault.png
    - assets/components/images/typehome-statedefault.png
    - assets/components/images/typestats-statedefault.png
    - assets/components/images/typesearch-history-statedefault.png
    - assets/components/images/typeprofile-statedefault.png
    - assets/components/images/vector-14-F4Z.png
    - assets/components/images/vector-14-RUR.png
    - assets/components/images/typenotification-indicator-statedefault.png
    - assets/components/images/vector-14-bcR.png
    - assets/components/images/product-category-icons-Csf.png
    - assets/components/images/typeshow-statedefault.png
    - assets/components/images/typehide-statedefault.png
    - assets/components/images/typelog-out-statedefault.png
    - assets/components/images/icons-pvh.png
    - assets/components/images/typeproducts-statedefault.png
    - assets/components/images/typeprivacy-statedefault.png
    - assets/components/images/typeheart-stateenabled.png
    - assets/components/images/typeaccount-settings-statedefault.png
    - assets/components/images/product-category-icons-qU1.png
    - assets/components/images/vector-4tV.png
    - assets/components/images/group-123.png
    - assets/components/images/typeheart-statedefault.png
    - assets/components/images/icons-zSq.png
    - assets/components/images/vector-ZpR.png
    - assets/components/images/group-Fx9.png
    - assets/components/images/rectangle-227.png
    - assets/components/images/typehygiene.png
    - assets/components/images/typemakeup.png
    - assets/components/images/typeall-products.png
    - assets/colors/images/shades.png
    - assets/components/images/icons-NL5.png
    - assets/components/images/typecleaning.png
    - assets/components/images/typeskincare.png
    - assets/components/images/typebody-care.png
    - assets/components/images/vector-14-A8V.png
    - assets/colors/images/shades-eJZ.png
    - assets/colors/images/shades-kEH.png
    - assets/colors/images/shades-FRw.png
    - assets/colors/images/shades-BKb.png
    - assets/colors/images/shades-7DF.png
    - assets/colors/images/group-3.png
    - assets/colors/images/shades-2CD.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
